// array of responses
let responses = []

// responses
let response1 = "<h1>Reading #1</h1><p class=\"reading-response\">For a long time, I have known web pages as sources that contain information that I need to understand and learn more for my academic research, to help me complete my coursework, and to answer any questions or concerns that I encounter as I live my life. My academic life as an engineering student has taught me the art of Googling, which showed me that the web is a place of endless information and knowledge. My 'handmade web' is often simply a place for me to put what I learn into practice, demonstrating that I have acquired yet another skill as a computer science student. I believe I am speaking for many computer science students when I say that our homepage is a place for us to display our work and skills; a supplement to our one-page resume on our applications. In a lot of ways, we are the amateurs mentioned in <a class=\"reading-link\" href=\"http://contemporary-home-computing.org/vernacular-web-2/\"target=\"_blank\">Olia Lialina's <i>Vernacular Web 2</i></a>. We often seek out existing tools, templates, or platforms created by others to help us achieve our goals rather than reinventing the wheel because it is just much more efficient and overall seems like the smartest approach. In this way, the web may not always be very transparent for those who code websites as well. Perhaps there is beauty to reinventing the wheel that could help inspire the appreciation and excitement for the web's existence that seems to be lacking in the community that I solely view as a marketplace of information.</p><br /><h2>Links to readings</h2><ul><li><a class=\"reading-link\" href=\"http://luckysoap.com/statements/handmadeweb.html\"target=\"_blank\">J. R. CARPENTER, <i>2015 A Handmade Web</i></a></li><li><a class=\"reading-link\" href=\"http://contemporary-home-computing.org/vernacular-web-2/\"target=\"_blank\">Olia Lialina, 2012, <i>Vernacular Web 2</i></a></li><li><a class=\"reading-link\" href=\"https://thecreativeindependent.com/essays/laurel-schwulst-my-website-is-a-shifting-house-next-to-a-river-of-knowledge-what-could-yours-be/\"target=\"_blank\">Laurel Schwulst, 2018, <i>My website is a shifting house next to a river of knowledge. What could yours be?</i></a></li></ul>"

let response2 = "<h1>Reading #2</h1><p class=\"reading-response\">I find <a class=\"reading-link\" href=\"https://www.are.na/block/7751270\"target=\"_blank\">Rosa Menkman's <i>Glitch Studies Manifesto</i></a> very thought-provoking, especially the discussion of “noise” within a social context. Rosa points out that noise often stands for “unaccepted sounds” and “(often undesirable, unwanted, other and unordered) disturbance, break, or addition within the signal of useful data.” These negative definitions of “noise” remind me of what we refer to as “noise” in the context of data collection and any fields that require the use of data, such as data science and machine learning. Throughout my past research experience, I observed how noisy data can negatively affect my results, and I learned data cleaning techniques that can be used to reduce the noise. Noisy data, in a way, can be viewed as glitches in data, which then cause glitches in trained models. Data scientists spend most of their time on data collection and cleaning to ensure that noisy data will not negatively impact the models that are trained using this data. If a trained model behaves in an unexpected manner, it is almost automatically assumed that something is wrong with the data, that maybe there is still noise in the data. The <i>Glitch Studies Manifesto</i> presents noise as a paradox; while it is often negatively defined, it could cause positive consequences. This makes me wonder about what the positive consequences could be for noisy data. Perhaps noisy data could actually reveal some insights about the model that is trained or the world that the model (and creator of the model) does not consider.</p><br /><h2>Links to readings</h2><ul><li><a class=\"reading-link\" href=\"https://rhizome.org/editorial/2016/oct/27/cyberfeminist-worldbuilding/\"target=\"_blank\">Claire Evans, 2016, <i>Feminist Worldbuilding in the Australian Cyberswamp</i></a></li><li><a class=\"reading-link\" href=\"https://anthology.rhizome.org/a-cyber-feminist-manifesto-for-the-21st-century\"target=\"_blank\">VNS Matrix, <i>A cyberfeminist manifesto</i></a></li><li><a class=\"reading-link\" href=\"https://www.are.na/block/7751270\"target=\"_blank\">Rosa Menkman, <i>Glitch Studies Manifesto</i></a></li><li><a class=\"reading-link\" href=\"https://cyberfeminismindex.com/about/\"target=\"_blank\">Mindy Seu, <i>Cyberfeminist Index - About</i></a></li></ul>"

let response3 = "<h1>Reading #3</h1><p class=\"reading-response\">The introduction and chapter one of <a class=\"reading-link\" href=\"http://www.asounder.org/resources/galloway_protocol.pdf\"target=\"_blank\">Alexander Galloway's <i>Protocol</i></a> explains the history of how the Internet came to be, how it works, and how it is a distributed system that is both at the same time decentralized and highly controlled. One of the motivations behind Galloway's book is discussing and answering the question: How would control exist after decentralization? He argues that “protocol is how technological control exists after decentralization.” When thinking about distributed systems and protocols, I am reminded of the different coding languages that we can use and the rules that come with these languages; coding is distributed and each language has its own set of “protocols” that we must learn and follow as programmers using the language. Coding languages are not centralized, meaning that there is no one set of language and rules that is used to program everything that exists. Instead, multiple languages and rules are developed for different or sometimes the same purposes, and communities form to maintain and grow these languages. Coding languages are not decentralized because while there seems to be absolute control through the creator's setting of rules that regulate how each language is used, these rules are often influenced and modified by the community that actively uses and cares about the language. Instead of these language rules being absolute control, they are more like agreements or guidelines that are first drafted by one person (the creator) and can later be updated as more people begin to join in (the collaborators).</p><br /><h2>Links to readings</h2><ul><li><a class=\"reading-link\" href=\"https://hub.xpub.nl/systers/mediawiki/index.php?title=A_Feminist_Server_Manifesto\"target=\"_blank\"><i>Feminist Server Manifesto</i></a></li><li><a class=\"reading-link\" href=\"http://www.asounder.org/resources/galloway_protocol.pdf\"target=\"_blank\">Alexander Galloway's <i>Protocol</i></a></li></ul>"

let response4 = "<h1>Reading #4</h1><p class=\"reading-response\"><a class=\"reading-link\" href=\"https://frankchimero.com/blog/2013/what-screens-want/\"target=\"_blank\">Frank Chimero, in <i>What Screens Want</i></a>, discusses the similarities between the progression of plastic and software and states “It's a pattern of malleable mediums: if something can be anything, it usually becomes everything.” Software, like plastic, started out as something that needed to look exactly like the thing that it is replacing to be accepted by its users. Screens, for example, were transformed from its default black to white to emulate the blank paper that is often seen in daily life. This transformation proved to be popular among consumers as the white-screened Apple Lisa outsold the black-screened Apple II (<a class=\"reading-link\" href=\"https://arena-attachments.s3.amazonaws.com/18633229/afaa715fb76fbe956e962077d98f551f.pdf?1666469092\"target=\"_blank\"><i>Black Gooey Universe</i></a>). However, overtime, as software, like plastic, became more ubiquitous, we realized that we can do things with it that we cannot do with the real things that it once imitated; we realized that software can become anything. The recently popular trend, dark mode, can be seen as a step backwards for some as it is an option for users to revert back to the default black that dates back to the very first screens. Personally, I think the popularity of dark mode is a step in the forward direction, recognizing that software does not have to be limited to the thing that it is imitating; as Bert Keely, a semi-retired Silicon valley designer says, “we're beyond paper” (<a class=\"reading-link\" href=\"https://eyeondesign.aiga.org/a-brief-history-of-dark-mode-from-the-matrix-like-displays-of-the-early-80s-to-today/\"target=\"_blank\"><i>A Brief History of “Dark Mode”</i></a>). Perhaps dark mode is a sign that we are undergoing a transformation where we are now building what we want rather than what we expect.</p><br /><h2>Links to readings</h2><ul><li><a class=\"reading-link\" href=\"https://arena-attachments.s3.amazonaws.com/18633229/afaa715fb76fbe956e962077d98f551f.pdf?1666469092\"target=\"_blank\">American Artist, <i>Black Gooey Universe</i></a></li><li><a class=\"reading-link\" href=\"https://frankchimero.com/blog/2013/what-screens-want/\"target=\"_blank\">Frank Chimero, <i>What Screens Want</i></a></li><li><a class=\"reading-link\" href=\"https://listen.datasociety.net/episodes/dark-patterns-in-accessibility-tech\"target=\"_blank\">Chancey Fleet, <i>Dark Patterns in Accessibility Tech</i></a></li><li><a class=\"reading-link\" href=\"https://interfacemanifesto.hangar.org/\"target=\"_blank\"><i>Critical Interface Manifesto</i></a></li></ul>"

let response5 = "<h1>Reading #5</h1><p class=\"reading-response\">One of the first, and perhaps most important, things that I learned in my big data course is that data is an asset that has become just as valuable as oil. Companies that hold more data also hold more power since they can use it to generate more profit. Because of the vast quantity of collected data, cleaning, processing, and analyzing large amounts of data become crucial skills that companies value. This is why, as my professor says, big data is an essential course to take; acquiring the skills necessary to make use of the collected data is equally as important as the data itself. While we learn to work with and understand large data collections, one thing we seem to overlook is where the data come from or how it is collected. <a class=\"reading-link\" href=\"https://archive.org/details/shoshanazubofftheageofsurveillancecapitalism/mode/2up\"target=\"_blank\">Shoshanna Zuboff, in <i>The Age of Surveillance Capitalism</i></a>, brings up the discussion of surveillance capitalism, where consumers, often unknowingly, fall into the cycle of producing data for companies to analyze and produce new products for purchase and use. Companies strategically and inevitably collect data from its consumers through its products and services that are becoming increasingly personalized and close-to-home, such as the Google Home and Amazon Alexa. Zuboff poses the question, “Can the digital future be our home?” I think that technology has, and will continue to, invade our homes whether we like it or not; but how can we make sure that our homes remain <i>ours</i>? Perhaps the first step is to become more knowledgeable and mindful consumers of technology.</p><br /><h2>Links to readings</h2><ul><li><a class=\"reading-link\" href=\"https://archive.org/details/shoshanazubofftheageofsurveillancecapitalism/mode/2up\"target=\"_blank\">Shoshana Zuboff, 2019, Introduction, <i>The Age of Surveillance Capitalism</i></a></li><li><a class=\"reading-link\" href=\"https://thebaffler.com/latest/capitalisms-new-clothes-morozov\"target=\"_blank\">Evgeny Morozov, February 4, 2019, <i>Capitalism's New Clothes</i></a></li></ul>"

window.onload = function(){
    // add responses to array
    responses.push(response1);
    responses.push(response2);
    responses.push(response3);
    responses.push(response4);
    responses.push(response5);

    // get the modal
    let modal = document.getElementById("myModal");
    // get all the readings
    let readings = document.getElementsByClassName("link");
    // get reading response
    let readingResponse = document.getElementsByClassName("modal-content")[0];

    for (let i = 0; i < readings.length; i++) {
        let reading = readings[i];

        // only look at the ones with p tag (i.e. those are the readings)
        if (reading.tagName == "P"){
            // attach click listener for each reading
            reading.onclick = function(event){
                modal.style.display = "block";
                responseIdx = parseInt(reading.innerHTML.split("#")[1])-1;
                readingResponse.innerHTML = responses[responseIdx];
            }
        }
    }

    // get the <span> element that closes the modal
    let span = document.getElementsByClassName("close")[0];

    // when the user clicks on <span> (x), close the modal
    span.onclick = function() {
      modal.style.display = "none";
    }

    // when the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }
}